### ISSUE TITLE
Usage of plugin

### ISSUE THREAD

**Issue by Juris3D** [darbycostello/RVO3D#1]
Hello! I do understnad this is "work in progress", probably not ready, but still - please could be there some short "how to", or UE map example, to try this? Thank You! :)

**Comment by darbycostello** [comment]
I'll try to get around to it, I've a lot of commercial work on at the moment. In the mean time I can give you the basic premise. 

- The plugin comprises two actor components; a simulator and an agent. 
- You add a simulator component to a level-wide actor (e.g. your GameMode BP) and you add the agent component to any actors that you need RVO avoidance for. 
- Call the **SetSimulatorActor** node in the **Event BeginPlay** of your agent actor and set it to a reference for the level-wide actor, as set up above. This registers the agent with the simulation.
- The agent actor's movement will now be used within the RVO simulation and you can query whether the agent needs to apply an avoidance velocity with the node **HasAvoidanceVelocity**. Typically this can be called in your agent actor's **Event Tick.**
- If this node returns _True_ then you should get the calculated avoidance velocity with the node **GetAvoidanceVelocity**. This will give you a vector of the velocity required by this agent to avoid a collision with any and all other simulated agents. How you implement or apply this avoidance vector is up to you however. The plugin simply performs the calculations; you may need to limit the final actor velocity based on your game constraints (e.g. scaled for capital ship mass and momentum).

**Comment by darbycostello** [comment]
As a side-note, like UE's built-in 2D RVO solution this plugin does not perform any collision checks for the avoidance velocity, so you may have some extra work to ensure your agents don't go careening into your level geometry instead of each other!

**Comment by Juris3D** [comment]
Thanks a lot for your answer! Appreciated!
